name: Build React App

on:
  push:
    branches: [ "main" ]

jobs:
  build_my_app:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Download your code to the virtual machine
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Install Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Compile the app
    - name: Run Build
      env:
        VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
      run: npm run build

    # Step 5: Save the 'dist' or 'build' folder so you can download it
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: production-files
        path: dist # Change to 'build' if using Create React App

    # Step 6: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # Change to './build' if using Create React App